# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-10 08:42
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_tweet_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tweet',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
