# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-14 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_auto_20180210_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='content',
            new_name='tweet',
        ),
    ]
