# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-19 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0011_auto_20180214_2025'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tweet',
            managers=[
            ],
        ),
    ]
