# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-20 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0012_auto_20180219_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['timestamp']},
        ),
    ]
